"""
Nifty-universe intraday BUY/SELL scan: same sr_volume model as the
commodity/index cards, applied across the STOCK SCREENER APP's own scanned
stock universe, filtered through its existing circuit-safety liquidity
gate so a pick can't be one that locks at LC/UC with no exit.

Reuses rather than reimplements:
  - intraday_candidate_gates_pass() from the screener's screener_engine.py
    (MTF/large-cap/mid-cap + >=Rs5Cr traded value -- the tested proxy this
    codebase already uses to keep intraday picks out of circuit bands).
  - screener_data.json, the screener's own latest scan output, read only --
    this app never writes to it. It's regenerated by the screener's daily
    scan job, so a stale local copy would drift; this always reads live
    from that path rather than caching a snapshot here.
  - sr_volume.py's compute_signal(), the same volume-backed S/R model
    running on the commodity/index cards.

The security-id map (NSE equity, ~9800 rows) changes only when new stocks
list/delist, so it's cached locally with a long TTL -- unlike the scan
data, this one IS safe to snapshot.
"""
import csv
import io
import json
import os
import sys
import time

import pandas as pd
import requests

import signal_engine

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# screener_data.json now lives alongside this app (fetch_and_build.py writes
# it here) rather than in the old standalone STOCK SCREENER APP folder --
# env-overridable for anyone still running that separate layout.
SCREENER_APP_DIR = os.environ.get("SCREENER_APP_DIR", BASE_DIR)
SCREENER_DATA_PATH = os.environ.get("SCREENER_DATA_PATH", os.path.join(SCREENER_APP_DIR, "screener_data.json"))

SECURITY_ID_CACHE_FILE = os.path.join(BASE_DIR, "nse_equity_security_ids.json")
SECURITY_ID_CACHE_TTL_SEC = 24 * 3600

INDMONEY_BASE_URL = "https://api.indstocks.com"
# Docs cap historical at 5 scrip-codes/call; observed rate limit is
# 10 req/sec/endpoint -- stay under it deliberately rather than at the edge.
BATCH_SIZE = 5
REQUESTS_PER_SEC = 6


def _token() -> str:
    tok = os.environ.get("INDMONEY_ACCESS_TOKEN")
    if not tok:
        raise RuntimeError("INDMONEY_ACCESS_TOKEN is not set")
    return tok


def _screener_engine():
    if SCREENER_APP_DIR not in sys.path:
        sys.path.insert(0, SCREENER_APP_DIR)
    import screener_engine as se
    return se


_screener_data_cache: list[dict] | None = None


def load_screener_data() -> list[dict]:
    """The one place screener_data.json actually gets read off disk.
    equity_scan, swing_engine, lt_engine, and penny_engine all scan
    overlapping slices of the same ~2,500-row file; before this, each of
    them opened and json.load()'d its own independent copy, so a single
    background-thread wakeup (all their loops fire close together) could
    hold 4+ copies of an 11MB structure in memory at once -- the direct
    cause of the free-tier 512MB OOM kill on Render. Cached for this
    process's lifetime: the file is a scan snapshot that only changes on
    a fresh deploy, never while this process is running, so there is no
    correctness cost to reading it once. Callers must copy a row (dict(row))
    before mutating it, since this list is shared -- every caller in this
    codebase already does."""
    global _screener_data_cache
    if _screener_data_cache is not None:
        return _screener_data_cache
    if not os.path.exists(SCREENER_DATA_PATH):
        print(f"[equity_scan] no scan data at {SCREENER_DATA_PATH} -- run fetch_and_build.py "
              f"and commit screener_data.json, or set SCREENER_DATA_PATH")
        _screener_data_cache = []
        return _screener_data_cache
    with open(SCREENER_DATA_PATH, encoding="utf-8") as f:
        _screener_data_cache = json.load(f)
    return _screener_data_cache


def load_liquid_candidates() -> list[dict]:
    """Every screener_data.json row that clears intraday_candidate_gates_pass --
    the same liquidity/circuit-safety bar the live screener's own intraday
    tab uses."""
    se = _screener_engine()
    return [r for r in load_screener_data() if se.intraday_candidate_gates_pass(r)]


def _refresh_security_id_cache() -> dict:
    resp = requests.get(f"{INDMONEY_BASE_URL}/market/instruments", params={"source": "equity"},
                         headers={"Authorization": _token()}, timeout=60)
    resp.raise_for_status()
    mapping = {
        row["TRADING_SYMBOL"]: row["SECURITY_ID"]
        for row in csv.DictReader(io.StringIO(resp.text))
        if row.get("EXCH") == "NSE" and row.get("INSTRUMENT_NAME") == "EQUITY"
    }
    with open(SECURITY_ID_CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump({"at": time.time(), "map": mapping}, f)
    return mapping


def get_security_id_map() -> dict:
    if os.path.exists(SECURITY_ID_CACHE_FILE):
        with open(SECURITY_ID_CACHE_FILE, encoding="utf-8") as f:
            cached = json.load(f)
        if time.time() - cached.get("at", 0) < SECURITY_ID_CACHE_TTL_SEC:
            return cached["map"]
    return _refresh_security_id_cache()


QUOTES_BATCH_SIZE = 350  # /market/quotes/full 414'd at 750 codes (~7.6KB URL); 350 stays safely under that


def fetch_live_quotes_batch(scrip_codes: list[str]) -> dict:
    """One /market/quotes/full call for up to QUOTES_BATCH_SIZE codes --
    that endpoint has no documented 5-code cap (unlike /historical), just a
    URL-length limit, so the whole ~724-stock universe fits in 2-3 calls
    instead of the historical endpoint's 145. Returns {scrip_code: {"ltp":
    ..., "volume": ...}}; a missing/delisted code is simply absent."""
    resp = requests.get(f"{INDMONEY_BASE_URL}/market/quotes/full", params={"scrip-codes": ",".join(scrip_codes)},
                         headers={"Authorization": _token()}, timeout=30)
    resp.raise_for_status()
    data = resp.json().get("data") or {}
    return {code: {"ltp": node.get("live_price"), "volume": node.get("volume")}
            for code, node in data.items() if node}


def fetch_live_quotes_for_symbols(symbols: list[str]) -> dict[str, dict]:
    """Live ltp + day change/% for a small, named list of symbols (e.g. the
    momentum scan's current top-20 picks) -- one batched call, well within
    QUOTES_BATCH_SIZE for any realistic watchlist size. Used for the 3s
    fast-poll on the /scan page, kept separate from scan_intraday_momentum's
    full-universe pass so a tight price refresh doesn't require re-scoring
    all 724 candidates every tick. Returns {symbol: {"ltp":, "change":,
    "change_pct":}}; a symbol with no live quote (e.g. delisted since the
    last full scan) is simply absent."""
    sec_map = get_security_id_map()
    code_to_symbol = {f"NSE_{sec_map[sym]}": sym for sym in symbols if sym in sec_map}
    if not code_to_symbol:
        return {}
    resp = requests.get(f"{INDMONEY_BASE_URL}/market/quotes/full",
                         params={"scrip-codes": ",".join(code_to_symbol.keys())},
                         headers={"Authorization": _token()}, timeout=15)
    resp.raise_for_status()
    data = resp.json().get("data") or {}
    out = {}
    for code, symbol in code_to_symbol.items():
        node = data.get(code)
        if not node:
            continue
        out[symbol] = {
            "ltp": node.get("live_price"),
            "change": node.get("day_change"),
            "change_pct": node.get("day_change_percentage"),
        }
    return out


def scan_intraday_momentum(top_n: int = 10) -> dict:
    """The screener's own intraday tab logic (compute_intraday_picks --
    day-move + volume + RSI + momentum + relative-strength composite,
    ranked and gated by the same circuit-safety rule as scan_universe())
    run with LIVE INDmoney price and volume instead of the screener's own
    yfinance-polled snapshot, which goes stale between its own refresh
    cycles. RSI/momentum/rs_rating/ma50/avg_volume_10d are read from
    screener_data.json unchanged -- those are daily-timeframe technicals
    that don't need a live refresh, only today's price/volume do.

    Deliberately calls compute_intraday_picks() itself rather than
    reimplementing its scoring -- Abhilash's own read is that the
    screener's intraday tab "works quite nicely"; the fix here is fresher
    inputs, not a different model.
    """
    se = _screener_engine()
    candidates = load_liquid_candidates()
    sec_map = get_security_id_map()

    by_symbol = {c["symbol"]: c for c in candidates if c["symbol"] in sec_map}
    scrip_to_symbol = {f"NSE_{sec_map[sym]}": sym for sym in by_symbol}
    all_codes = list(scrip_to_symbol.keys())

    live_by_code: dict = {}
    for i in range(0, len(all_codes), QUOTES_BATCH_SIZE):
        batch = all_codes[i:i + QUOTES_BATCH_SIZE]
        try:
            live_by_code.update(fetch_live_quotes_batch(batch))
        except Exception as e:
            print(f"[equity_scan] live quotes batch failed ({len(batch)} codes): {e}")

    updated_rows, stale_count = [], 0
    for code, symbol in scrip_to_symbol.items():
        row = dict(by_symbol[symbol])
        live = live_by_code.get(code)
        if not live or live.get("ltp") is None:
            stale_count += 1
            updated_rows.append(row)  # keep the cached row rather than drop the candidate entirely
            continue
        row["ltp"] = live["ltp"]
        avg_vol = row.get("avg_volume_10d") or 0
        if avg_vol > 0 and live.get("volume") is not None:
            row["volume_spike"] = round(live["volume"] / avg_vol, 2)
            row["today_volume"] = live["volume"]
        updated_rows.append(row)

    picks = se.compute_intraday_picks(updated_rows, top_n=top_n)
    picks["scanned"] = len(updated_rows)
    picks["stale_ltp_count"] = stale_count
    print(f"[equity_scan] intraday momentum: {len(updated_rows)} scanned, {stale_count} stale, "
          f"{len(picks['buy'])} buy / {len(picks['sell'])} sell picks "
          f"(qualified {picks['buy_qualified']}/{picks['sell_qualified']})")
    return picks


def fetch_hourly_candles_batch(scrip_codes: list[str], days: int = 14) -> dict:
    """One historical call for up to BATCH_SIZE scrip-codes. Returns
    {scrip_code: DataFrame}; a scrip-code with no data is simply absent,
    not an error -- illiquid names sometimes have thin/gappy history."""
    end_ms = int(time.time() * 1000)
    start_ms = end_ms - days * 24 * 3600 * 1000
    _t0 = time.time()
    resp = requests.get(f"{INDMONEY_BASE_URL}/market/historical/60minute",
                         params={"scrip-codes": ",".join(scrip_codes), "start_time": start_ms, "end_time": end_ms},
                         headers={"Authorization": _token()}, timeout=30)
    print(f"[equity_scan] request for {scrip_codes} took {round(time.time() - _t0, 2)}s, status {resp.status_code}")
    resp.raise_for_status()
    payload = resp.json()
    out = {}
    for code, series in (payload.get("data") or {}).items():
        candles = series.get("candles") or []
        if not candles:
            continue
        df = pd.DataFrame(candles).rename(
            columns={"o": "Open", "h": "High", "l": "Low", "c": "Close", "v": "Volume"})
        out[code] = df[["Open", "High", "Low", "Close", "Volume"]]
    return out


def classify_watch_tier(sig: dict, ltp: float) -> str | None:
    """sr_volume only fires BUY/SELL on a *confirmed turn* at a level, which
    is deliberately strict and can leave a whole universe with almost no
    signal (724 stocks -> 1 SELL was the actual count on 2026-09-11). This
    adds a lower-conviction tier for stocks currently sitting near a
    volume-defended level but not yet confirmed turning -- worth watching,
    not worth acting on. Approximates sr_volume's own internal proximity
    check (which uses a recent-bars touch, not raw ltp) using the public
    srv_support/srv_resistance/srv_box_depth fields already returned,
    without forking sr_volume.py itself."""
    if sig.get("srv_signal") in ("BUY", "SELL") or not sig.get("srv_available"):
        return None
    depth = sig.get("srv_box_depth") or 0
    if depth <= 0 or not ltp:
        return None
    import sr_volume
    near = depth * float(sr_volume.GATES["near_box_mult"])

    support, resistance = sig.get("srv_support"), sig.get("srv_resistance")
    if support is not None and ltp > support and (ltp - support) <= near:
        return "WATCH_BUY"
    if resistance is not None and ltp < resistance and (resistance - ltp) <= near:
        return "WATCH_SELL"
    return None


def scan_universe(top_n: int = 10, max_candidates: int | None = None) -> dict:
    """Full pipeline: liquid candidates -> batched 1H candles -> sr_volume
    signal -> top `top_n` BUY and top `top_n` SELL by srv_strength, plus a
    WATCH tier (see classify_watch_tier) for stocks near a level but not
    yet confirmed turning. `max_candidates` caps how many stocks are
    scanned, for a quick test run."""
    import sr_volume

    print("[equity_scan] loading liquid candidates...")
    candidates = load_liquid_candidates()
    if max_candidates:
        candidates = candidates[:max_candidates]
    print(f"[equity_scan] {len(candidates)} liquid candidates, resolving security IDs...")

    sec_map = get_security_id_map()
    by_symbol = {c["symbol"]: c for c in candidates if c["symbol"] in sec_map}
    scrip_to_symbol = {f"NSE_{sec_map[sym]}": sym for sym in by_symbol}
    all_codes = list(scrip_to_symbol.keys())

    buys, sells, watch_buys, watch_sells, skipped = [], [], [], [], 0
    call_interval = 1.0 / (REQUESTS_PER_SEC / BATCH_SIZE)
    total_batches = (len(all_codes) + BATCH_SIZE - 1) // BATCH_SIZE
    scan_started = time.time()
    print(f"[equity_scan] starting: {len(all_codes)} symbols, {total_batches} batches")

    for i in range(0, len(all_codes), BATCH_SIZE):
        batch_num = i // BATCH_SIZE + 1
        if batch_num == 1 or batch_num % 20 == 0 or batch_num == total_batches:
            print(f"[equity_scan] batch {batch_num}/{total_batches}, "
                  f"{round(time.time() - scan_started, 1)}s elapsed")
        batch = all_codes[i:i + BATCH_SIZE]
        t0 = time.time()
        try:
            candle_map = fetch_hourly_candles_batch(batch)
        except Exception as e:
            print(f"  [warn] batch fetch failed for {batch}: {e}")
            skipped += len(batch)
            continue

        for code in batch:
            symbol = scrip_to_symbol[code]
            df = candle_map.get(code)
            if df is None or len(df) < sr_volume.GATES["min_bars"]:
                skipped += 1
                continue
            sig = sr_volume.compute_signal(df, signal_engine.INTRADAY_SR_GATES)
            row = by_symbol[symbol]
            ltp = row.get("ltp")
            entry = {
                "symbol": symbol, "name": row.get("name") or symbol, "sector": row.get("sector"),
                "ltp": ltp, **sig,
            }
            if sig.get("srv_signal") == "BUY":
                buys.append(entry)
            elif sig.get("srv_signal") == "SELL":
                sells.append(entry)
            else:
                tier = classify_watch_tier(sig, ltp)
                if tier == "WATCH_BUY":
                    entry["dist_to_level"] = round(abs(ltp - sig["srv_support"]), 2) if ltp and sig.get("srv_support") else None
                    watch_buys.append(entry)
                elif tier == "WATCH_SELL":
                    entry["dist_to_level"] = round(abs(ltp - sig["srv_resistance"]), 2) if ltp and sig.get("srv_resistance") else None
                    watch_sells.append(entry)

        elapsed = time.time() - t0
        if elapsed < call_interval:
            time.sleep(call_interval - elapsed)

    buys.sort(key=lambda x: x["srv_strength"], reverse=True)
    sells.sort(key=lambda x: x["srv_strength"], reverse=True)
    # Nearer the level = more worth watching, so sort ascending on distance.
    watch_buys.sort(key=lambda x: x["dist_to_level"] if x["dist_to_level"] is not None else float("inf"))
    watch_sells.sort(key=lambda x: x["dist_to_level"] if x["dist_to_level"] is not None else float("inf"))

    print(f"[equity_scan] done in {round(time.time() - scan_started, 1)}s: "
          f"{len(buys)} buy, {len(sells)} sell, {len(watch_buys)} watch_buy, "
          f"{len(watch_sells)} watch_sell, {skipped} skipped")

    return {
        "scanned": len(all_codes), "skipped_no_data": skipped,
        "buy": buys[:top_n], "sell": sells[:top_n],
        "buy_qualified": len(buys), "sell_qualified": len(sells),
        "watch_buy": watch_buys[:top_n], "watch_sell": watch_sells[:top_n],
        "watch_buy_qualified": len(watch_buys), "watch_sell_qualified": len(watch_sells),
    }


if __name__ == "__main__":
    with open(os.path.join(BASE_DIR, "indmoney.env"), encoding="utf-8") as f:
        for line in f:
            if line.startswith("INDMONEY_ACCESS_TOKEN="):
                os.environ["INDMONEY_ACCESS_TOKEN"] = line.strip().split("=", 1)[1]

    result = scan_universe(top_n=10)
    print(f"scanned={result['scanned']} skipped={result['skipped_no_data']} "
          f"buy_qualified={result['buy_qualified']} sell_qualified={result['sell_qualified']}")
    print("\n=== TOP 10 BUY ===")
    for r in result["buy"]:
        print(f"  {r['symbol']:<15} ltp={r['ltp']:<10} entry={r['srv_entry']} stop={r['srv_stop']} "
              f"t1={r['srv_target1']} strength={r['srv_strength']} - {r['srv_reason']}")
    print("\n=== TOP 10 SELL ===")
    for r in result["sell"]:
        print(f"  {r['symbol']:<15} ltp={r['ltp']:<10} entry={r['srv_entry']} stop={r['srv_stop']} "
              f"t1={r['srv_target1']} strength={r['srv_strength']} - {r['srv_reason']}")
    print(f"\n=== WATCH BUY ({result['watch_buy_qualified']} total, near support) ===")
    for r in result["watch_buy"]:
        print(f"  {r['symbol']:<15} ltp={r['ltp']:<10} support={r['srv_support']} dist={r['dist_to_level']}")
    print(f"\n=== WATCH SELL ({result['watch_sell_qualified']} total, near resistance) ===")
    for r in result["watch_sell"]:
        print(f"  {r['symbol']:<15} ltp={r['ltp']:<10} resistance={r['srv_resistance']} dist={r['dist_to_level']}")
